[2024-12-22T09:16:07.769+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rickmorty.is_api_available manual__2024-12-22T09:16:05.711923+00:00 [queued]>
[2024-12-22T09:16:07.782+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rickmorty.is_api_available manual__2024-12-22T09:16:05.711923+00:00 [queued]>
[2024-12-22T09:16:07.782+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2024-12-22T09:16:07.803+0000] {taskinstance.py:1327} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-12-22 09:16:05.711923+00:00
[2024-12-22T09:16:07.812+0000] {standard_task_runner.py:57} INFO - Started process 156 to run task
[2024-12-22T09:16:07.817+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rickmorty', 'is_api_available', 'manual__2024-12-22T09:16:05.711923+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/rickmorty.py', '--cfg-path', '/tmp/tmpliry3hf2']
[2024-12-22T09:16:07.818+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask is_api_available
[2024-12-22T09:16:07.902+0000] {task_command.py:410} INFO - Running <TaskInstance: rickmorty.is_api_available manual__2024-12-22T09:16:05.711923+00:00 [running]> on host d49f0e0149ee
[2024-12-22T09:16:08.025+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rickmorty' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T09:16:05.711923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T09:16:05.711923+00:00'
[2024-12-22T09:16:08.026+0000] {http.py:122} INFO - Poking: api/
[2024-12-22T09:16:08.050+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 225, in execute
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 212, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 137, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 128, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 148, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 100, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `api` isn't defined
[2024-12-22T09:16:08.055+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=rickmorty, task_id=is_api_available, execution_date=20241222T091605, start_date=20241222T091607, end_date=20241222T091608
[2024-12-22T09:16:08.071+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2 for task is_api_available (The conn_id `api` isn't defined; 156)
[2024-12-22T09:16:08.112+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-22T09:16:08.176+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
